#!/usr/bin/env bash
# ---------------------------------------
# CYBRwall    hyprland random wallpaper script (part of cybrland)
# Project:    https://github.com/scherrer-txt/cybrland
# Author:     scherrer-txt   |   License:     GPL-3.0
# Source:     ~/.config/hypr/scripts/wallpaper-daemon
# ---------------------------------------

WALLPAPER_DIR="$HOME/.config/hypr/walls"
LAST_WALL="$HOME/.cache/last_wallpaper.txt"
TRIGGER="$HOME/.cache/wallpaper_trigger"
INTERVAL=900 # 60 = 1min; 900 = 15min

LOCK="/tmp/hyprpaper_daemon.lock"
exec 200>$LOCK
flock -n 200 || exit 0

choose() {
    find "$WALLPAPER_DIR" -type f | shuf -n 1
}

wait_for_hyprpaper() {
    while ! hyprctl hyprpaper listpreloaded &>/dev/null; do
        sleep 0.5
    done
}

switch_wall() {
    local wp="$1"
    hyprctl hyprpaper preload "$wp"
    sleep 0.2
    hyprctl hyprpaper wallpaper ",$wp"
}

notify_wall() {
    local wp="$1"

    if pgrep -x "hyprpaper" >/dev/null; then
        notify-send "Wallpaper Changed" -i "$wp" --app-name=Wallpaper
    elif pgrep -x "swww" >/dev/null; then
        notify-send "Wallpaper Changed" -i "$wp" --app-name=Wallpaper
    fi
}

wait_for_hyprpaper

while true; do
    if [ -f "$TRIGGER" ]; then
        rm "$TRIGGER"

        if [ -f "$LAST_WALL" ]; then
            new="$(cat "$LAST_WALL")"
        else
            new="$(choose)"
        fi
    else
        new="$(choose)"
    fi

    if [ -f "$LAST_WALL" ] && [ "$new" = "$(cat "$LAST_WALL")" ]; then
        :
    else
        echo "$new" > "$LAST_WALL"
        switch_wall "$new"
        notify_wall "$new"
    fi

    for ((i=0; i<INTERVAL; i++)); do
        [ -f "$TRIGGER" ] && break
        sleep 1
    done
done

# Run this after every change:
# systemctl --user daemon-reload && systemctl --user restart wallpaper-daemon.service && systemctl --user status wallpaper-daemon.service
